In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [70]:
df = pd.read_csv("test_case hard/Train.csv")
dftest = pd.read_csv("test_case hard/Test.csv")
xt = dftest.values
yt

array([[ 1.01525387e+00,  2.07620944e+00, -2.66434820e-01,
        -2.41808820e+00, -9.80502790e-01],
       [-3.75021204e-01,  9.53184528e-01,  6.26719138e-01,
         7.04405750e-01, -3.55489211e-01],
       [-1.02445225e+00,  9.62991107e-01, -4.07942004e-01,
        -1.86127383e+00,  4.55201351e-01],
       ...,
       [ 5.54727647e-01,  1.76824345e+00, -8.97787210e-01,
        -1.19366107e+00,  3.40563374e-01],
       [-1.62717246e+00,  8.56470994e-01, -5.65729519e-04,
         6.29386649e-01,  4.53382144e-01],
       [ 1.39310499e-01,  5.31597186e-01, -8.53107053e-01,
         3.16920076e-02,  1.71489304e+00]])

In [54]:
lr = LinearRegression(normalize=True)

In [64]:
dfx = df.iloc[:,0:5]
dfy = df[['target']]

x = dfx.values
y = dfy.values
y = y.reshape((1600,))
x

array([[ 0.29341624, -0.94559871, -0.42110515,  0.40681602,  0.52566183],
       [-0.83608408, -0.18922804, -0.77640262, -1.05383124,  0.59799685],
       [ 0.23642511,  0.13283602, -0.14772298,  0.69985396, -0.18736416],
       ...,
       [ 1.04417694, -0.89920649,  1.73039905, -1.87105676,  0.44251965],
       [-1.2691729 , -0.00505216,  1.85766873, -1.08036482,  0.73633394],
       [-1.88400025, -0.84942743, -1.45227035,  0.48861308,  1.4595758 ]])

In [56]:
lr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [62]:
m = lr.coef_
c = lr.intercept_

array([29.68187118, 92.66247759,  8.28062089, 44.76773522,  2.51916121])

In [71]:
rating= lr.score(x,y)
rating

0.9660939669975616

In [86]:
output = lr.predict(xt)
print(xt.shape)
output.shape
dfout = pd.DataFrame(output)
dfout.to_csv("test_case hard/airout.csv")

(400, 5)

In [90]:
dfout.columns = ['target']
dfout.index.name = 'Id'
dfout

         target
Id
0    114.583689
1    118.012815
2    -21.739852
3    -43.936899
4    -95.914898
5    -44.507424
6    -75.566526
7     23.820835
8    173.835284
9    172.849290
10  -105.402312
11   -20.802023
12    -3.913238
13   122.999186
14    40.307884
15    45.712850
16  -189.628491
17    22.612545
18    11.641047
19   136.342143
20    64.916255
21   -61.988488
22  -108.194679
23    -7.412127
24   -58.523953
25    11.888978
26    29.237640
27   107.687579
28    24.146856
29   -26.105012
..          ...
370 -137.921702
371  -50.514772
372  -93.679380
373    8.816282
374  -14.604027
375  -62.851997
376  -16.465554
377 -172.962640
378 -122.791775
379   45.273898
380  -37.309931
381 -157.438494
382   87.498386
383   -0.320726
384  133.257842
385  -47.172209
386    2.574661
387  174.227519
388  170.930081
389   46.433357
390  -26.720651
391   59.632252
392  111.659113
393  -36.502767
394  -69.139053
395  -81.989000
396 -186.032535
397  125.292336
398   65.369841
399   57.059691

[400 rows x 1 columns]

In [91]:
dfout.to_csv("test_case hard/airout.csv")